<?php
/**
 * This is the PLAIN TEXT template of email message for comment moderation reminders
 *
 * This file is not meant to be called directly.
 * It is meant to be called by an include in the main.page.php template.
 *
 * b2evolution - {@link http://b2evolution.net/}
 * Released under GNU GPL License - {@link http://b2evolution.net/about/license.html}
 * @copyright (c)2003-2013 by Francois Planque - {@link http://fplanque.com/}
 *
 * @package evoskins
 *
 * {@internal Below is a list of authors who have contributed to design/coding of this file: }}
 * @author attila: Attila Simo.
 *
 * @version $Id$
 */
if( !defined('EVO_MAIN_INIT') ) die( 'Please, do not access this page directly.' );

global $admin_url, $baseurl, $htsrv_url;

$BlogCache = & get_BlogCache();

// Default params:
$params = array_merge( array(
		'blogs'    => array(),
		'comments' => array(),
	), $params );

echo T_( 'Hello $login$ !' )."\n\n";

echo T_( 'There have been comments awaiting moderation for more than 24 hours in the following blogs:' );
echo "\n\n";

foreach( $params['blogs'] as $blog_ID )
{
	$moderation_Blog = $BlogCache->get_by_ID( $blog_ID );
	echo "\t - ".$moderation_Blog->get( 'shortname' ).' ('.sprintf( T_( '%s comments waiting' ), $params['comments'][$blog_ID] ).') - '.$admin_url.'?ctrl=dashboard&blog='.$blog_ID."\n";
}
echo "\n";

echo sprintf( T_( 'This message was automatically generated by b2evolution running on %s.' ), $baseurl );
echo "\n";
echo T_( 'Please do not reply to this email.' );
echo "\n";
echo T_( 'You are a moderator in this blog, and you are receiving notifications when a comments may need moderation.' )."\n";
echo T_( 'If you don\'t want to receive any more notifications about comment moderation, click here' ).': '
		.$htsrv_url.'quick_unsubscribe.php?type=moderator&user_ID=$user_ID$&key=$unsubscribe_key$';
echo "\n";
echo T_( 'Your login is: $login$' );
?>