<script src="<?php echo $b2inc ?>/_quicktags.js" language="JavaScript" type="text/javascript">
</script>

<input type="button" class="quicktags" accesskey="i" title="INSerted [Alt-I]" name="addbbcode4" value="ins" style="text-decoration: underline;" onClick="bbstyle(this.form,4)" /><input type="button" class="quicktags" accesskey="d" title="DELeted [Alt-D]" name="addbbcode6" value="del" style="text-decoration: line-through;" onClick="bbstyle(this.form,6)" /><input type="button" class="quicktags" accesskey="s" title="STRong [Alt-S]" name="addbbcode0" value="str" style="font-weight:bold;" onClick="bbstyle(this.form,0)" /><input type="button" class="quicktags" accesskey="e" title="EMphasis [Alt-T]" name="addbbcode2" value="em" style="font-style:italic;" onClick="bbstyle(this.form,2)" /><input type="button" class="quicktags" accesskey="c" title="CODE [Alt-C]" name="addbbcode20" value="code" style="font-family: 'Courier New', Courier, mono;" onClick="bbstyle(this.form,20)" /><input type="button" class="quicktags" accesskey="p" title="Paragraph [Alt-P]" name="addbbcode10" value="&lt;p&gt;" style="" onClick="bbstyle(this.form,10)" /><input type="button" class="quicktags" accesskey="u" title="Unordered List [Alt-U]" name="addbbcode18" value="&lt;ul&gt;" style="" onClick="bbstyle(this.form,18)" /><input type="button" class="quicktags" accesskey="l" title="List Item [Alt-L]" name="addbbcode12" value="&lt;li&gt;" style="" onClick="bbstyle(this.form,12)" /><input type="button" class="quicktags" accesskey="b"  title="BLOCKQUOTE [Alt-B]" name="addbbcode8" value="block" style="" onClick="bbstyle(this.form,8)" /><input type="button" class="quicktags" accesskey="g" title="IMaGe [Alt-G]" name="addbbcode14" value="image" style="width: 40px"  onClick="bblink(this.form,'img')" /><input type="button" class="quicktags" accesskey="a" title="A href [Alt-A]" name="addbbcode16" value="link" style="text-decoration: underline; width: 40px" onClick="bblink(this.form,'a')" /><input type="button" class="quicktags" accesskey="x" name="closetags" value="X" title="Close all tags" style="width: 30px; font-weigh: bolder;"  onClick="bbstyle(document.post,-1)" /><input type="button" class="quicktags" accesskey="m" title="More [Alt-M]" name="pagebreak" value="more" style="" onClick="bbinsert(document.post,'','<!--more-->')" /><input type="button" class="quicktags" accesskey="t" title="no teaser [Alt-T]" name="pagebreak" value="NT" style="" onClick="bbinsert(document.post,'','<!--noteaser-->')" />

<br />

<?php	// fplanque: added smiley block:
	foreach($b2smiliestrans as $smiley => $img) 
	{
		print '<img src="'.$smilies_directory.'/'.$img.'" alt="'.$smiley.'" class="middle"  onClick="bbinsert(document.post,\'\', \''.str_replace("'","\'",$smiley).'\')" /> '; // TODO: escape ' 	
	}
?>